WebApiBlueBank/WebBlueSoft/Models/CuentaAhorroViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebBlueSoft.Models
{
    public class CuentaAhorroViewModel
    {
        [Display(Name = "Numero De Cuenta de Ahorro")]
        public int NumeroCuenta { get; set; }

        [Required(ErrorMessage = "El campo es Obligatorio")]
        [Display(Name = "Nombre Completo del titular")]
        public string NombreTitular { get; set; }

        [Display(Name = "Valor Inicial")]
        public decimal ValorInicial { get; set; }

        [Display(Name = "Valor de consignación")]
        public decimal? ValorConsignacion { get; set; }

        [Display(Name = "Valor de Retiro")]
        public decimal? ValorRetiro { get; set; }

        public ICollection<CuentaAhorroViewModel> Data { get; set; }
    }
}

WebApiBlueBank/WebBlueSoft/Models/ErrorViewModel.cs
using System;

namespace WebBlueSoft.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApiBlueBank/WebBlueSoft/Controllers/CuentaAhorroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WebBlueSoft.Helper;
using WebBlueSoft.Models;

namespace WebBlueSoft.Controllers
{
    public class CuentaAhorroController : Controller
    {
        WebApi _api = new WebApi();


        public async Task<IActionResult> Index()
        {
            IEnumerable<CuentaAhorroViewModel> CuentaAhorro = null;
            HttpClient client = _api.Inicial();

            HttpResponseMessage res = await client.GetAsync("api/CuentaAhorro");
            if (res.IsSuccessStatusCode)
            {
                var results = res.Content.ReadAsStringAsync().Result;
                CuentaAhorro = JsonConvert.DeserializeAnonymousType (results, new { data = default(List<CuentaAhorroViewModel>) }).data;
            }
            return View(CuentaAhorro);
        }

        public async Task<IActionResult> Details(int Id)
        {

            var CuentaAhorro = new CuentaAhorroViewModel();
            HttpClient client = _api.Inicial();
            HttpResponseMessage res = await client.GetAsync($"api/CuentaAhorro/{Id}");
            if (res.IsSuccessStatusCode)
            {
                var results = res.Content.ReadAsStringAsync().Result;
                CuentaAhorro = JsonConvert.DeserializeAnonymousType(results, new { data = default(CuentaAhorroViewModel) }).data;
            }
            return View(CuentaAhorro);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CuentaAhorroViewModel CuentaAhorro)
        {
            HttpClient client = _api.Inicial();

            var postTask = client.PostAsJsonAsync<CuentaAhorroViewModel>("api/CuentaAhorro", CuentaAhorro);
            postTask.Wait();

            var result = postTask.Result;
            if (result.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            return View();
        }

        public async Task<IActionResult> Delete(int Id)
        {
            var Code = new CuentaAhorroViewModel();
            HttpClient client = _api.Inicial();
            HttpResponseMessage res = await client.DeleteAsync($"api/CuentaAhorro/{Id}");

            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Edit(int Id)
        {
            var CuentaAhorro = new CuentaAhorroViewModel();
            HttpClient client = _api.Inicial();
            HttpResponseMessage res = await client.GetAsync($"api/CuentaAhorro/{Id}");
            if (res.IsSuccessStatusCode)
            {
                var results = res.Content.ReadAsStringAsync().Result;
                CuentaAhorro = JsonConvert.DeserializeAnonymousType(results, new { data = default(CuentaAhorroViewModel)}).data;
                
            }
            return View(CuentaAhorro);

        }

        [HttpPost]
        public ActionResult Edit(CuentaAhorroViewModel CuentaAhorro)
        {
            HttpClient client = _api.Inicial();
            var putTask = client.PutAsJsonAsync<CuentaAhorroViewModel>($"api/CuentaAhorro", CuentaAhorro);
            putTask.Wait();

            var result = putTask.Result;
            if (result.IsSuccessStatusCode)
                return RedirectToAction("Index");
            return View(CuentaAhorro);


        }
        public async Task<ActionResult> Consignacion(int Id)
        {
            var CuentaAhorro = new CuentaAhorroViewModel();
            HttpClient client = _api.Inicial();
            HttpResponseMessage res = await client.GetAsync($"api/CuentaAhorro/{Id}");
            if (res.IsSuccessStatusCode)
            {
                var results = res.Content.ReadAsStringAsync().Result;
                CuentaAhorro = JsonConvert.DeserializeAnonymousType(results, new { data = default(CuentaAhorroViewModel) }).data;

            }
            return View(CuentaAhorro);

        }

        [HttpPost]
        public ActionResult Consignacion(CuentaAhorroViewModel CuentaAhorro)
        {
            HttpClient client = _api.Inicial();
            var putTask = client.PutAsJsonAsync<CuentaAhorroViewModel>($"api/CuentaAhorro", CuentaAhorro);
            putTask.Wait();

            var result = putTask.Result;
            if (result.IsSuccessStatusCode)
                return RedirectToAction("Index");
            return View(CuentaAhorro);

        }
        }
    }

WebApiBlueBank/WebBlueSoft/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebBlueSoft.Models;

namespace WebBlueSoft.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApiBlueBank/WebBlueSoft/Views/CuentaAhorro/Consignacion.cshtml
@model WebBlueSoft.Models.CuentaAhorroViewModel

@{
    ViewData["Title"] = "Consignacion";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Consignacion</h1>

<h4>CuentaAhorroViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Consignacion">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NumeroCuenta" class="control-label"></label>
                <input asp-for="NumeroCuenta" class="form-control" />
                <span asp-validation-for="NumeroCuenta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NombreTitular" class="control-label"></label>
                <input asp-for="NombreTitular" class="form-control" />
                <span asp-validation-for="NombreTitular" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ValorConsignacion" class="control-label"></label>
                <input asp-for="ValorConsignacion" class="form-control" />
                <span asp-validation-for="ValorConsignacion" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApiBlueBank/WebBlueSoft/Views/CuentaAhorro/Create.cshtml
@model WebBlueSoft.Models.CuentaAhorroViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-center">Crear Cuenta de Ahorros</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="NombreTitular" class="control-label"></label>
                <input asp-for="NombreTitular" class="form-control" />
                <span asp-validation-for="NombreTitular" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValorInicial" class="control-label"></label>
                <input asp-for="ValorInicial" class="form-control" />
                <span asp-validation-for="ValorInicial" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-success" />
                <a class="btn btn-info" role="button" asp-action="Index">Volver</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApiBlueBank/WebBlueSoft/Views/CuentaAhorro/Details.cshtml
@model WebBlueSoft.Models.CuentaAhorroViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-center">Información de la cuenta</h1>


<div>

    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NumeroCuenta)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NumeroCuenta)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NombreTitular)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NombreTitular)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ValorInicial)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ValorInicial)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ValorConsignacion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ValorConsignacion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ValorRetiro)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ValorRetiro)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Editar", "Edit", new { id = Model.NumeroCuenta }, new { @class = "btn btn-warning" })

    <a class="btn btn-success" role="button" asp-action="Index">Atras</a>
</div>

WebApiBlueBank/WebBlueSoft/Views/CuentaAhorro/Edit.cshtml
@model WebBlueSoft.Models.CuentaAhorroViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-center">Editar Cuenta</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NumeroCuenta" class="control-label"></label>
                <input asp-for="NumeroCuenta" class="form-control" />
                <span asp-validation-for="NumeroCuenta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NombreTitular" class="control-label"></label>
                <input asp-for="NombreTitular" class="form-control" />
                <span asp-validation-for="NombreTitular" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValorInicial" class="control-label"></label>
                <input asp-for="ValorInicial" class="form-control" />
                <span asp-validation-for="ValorInicial" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-success" />
                <a class="btn btn-info" role="button" asp-action="Index">Volver</a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApiBlueBank/WebBlueSoft/Views/CuentaAhorro/Index.cshtml
@model IEnumerable<WebBlueSoft.Models.CuentaAhorroViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-center">Listado de Cuentas</h1>

<p>
    <a class="btn btn-info" role="button" asp-action="Create">Crear cuenta de ahorros</a>
</p>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NumeroCuenta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NombreTitular)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ValorInicial)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ValorConsignacion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ValorRetiro)
            </th>
            <th>
                Opciones
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NumeroCuenta)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NombreTitular)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ValorInicial)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ValorConsignacion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ValorRetiro)
                </td>
                <td>
                    @Html.ActionLink("Editar", "Edit", new { id = item.NumeroCuenta }, new { @class = "btn btn-outline-warning" }) |
                    @Html.ActionLink("Consignar", "Consignacion", new { id = item.NumeroCuenta }, new { @class = "btn btn-outline-warning" }) |
                    @Html.ActionLink("Detalles", "Details", new { id = item.NumeroCuenta }, new { @class = "btn btn-outline-info" })
                </td>
            </tr>
        }
    </tbody>
</table>

WebApiBlueBank/WebBlueSoft/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<br />
<br />
<div class="text-center">
    <h1 class="display-4">Bienvenido al BlueBank</h1>
</div>
<br />
<br />
<br />

WebApiBlueBank/WebBlueSoft/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebBlueSoft</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebBlueSoft</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CuentaAhorro" asp-action="Index">Cuentas de Ahorro</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - WebBlueSoft - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>